minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit, commit-msg]

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md] # Do not process Markdown files.
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-toml

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: .*/__snapshots__/.*|.*-input\.json$|tests/.*

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML", "types-requests"]
        exclude: ^(docs/|.*test.*\.py$|.*/__pycache__/.*|dist/|build/|.*\.egg-info/.*)

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --subject-min-length=10
          - --subject-max-length=80

# Configuration for excluding files/directories
exclude: |
  (?x)^(
    dist/|
    build/|
    \.egg-info/|
    __pycache__/|
    \.git/|
    \.pytest_cache/|
    htmlcov/|
    \.venv/|
    venv/
  )$
